version: '3'

services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: <USER>
      POSTGRES_PASSWORD: <SECRET>
    volumes:
      - /mnt/db-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.keycloak==true"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-<EMAIL>}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-<SECRET>}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - /mnt/pgadmin-data:/var/lib/pgadmin
    networks:
      - backend
      - npm-public
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.keycloak==true"

networks:
  backend:
    external: true
  npm-public:
    external: true
